import "./globals.css";
import Header from "./_components/Header/page";
import Footer from "./_components/Footer/page";
import 'bootstrap/dist/css/bootstrap.min.css';

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        
        <link rel="stylesheet" href="../assets/style.css"></link>
      </head>
      <body>
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
